<?php
/**
 * Abstract base class for Velora Gutenberg block registration.
 *
 * Each block is dynamic (server-rendered) — its render callback delegates
 * to the corresponding shortcode, keeping one source of truth for output.
 * The editor preview uses the shared editor.js bundle.
 *
 * Distribution note: WordPress.org forbids a plugin from depending on another
 * plugin, so each plugin ships its own copy of this class. `make wp-plugins-build`
 * generates those copies with a per-plugin class prefix (Velora_Breeder_Base_*,
 * Velora_Club_Base_*): two plugins declaring the same global class name is a
 * fatal error the moment both are active on one site.
 * This file: GENERATED from shared/class-base-blocks.php by `make build-base`. DO NOT EDIT.
 *
 * @package VeloraWidgets
 */

if (!defined('ABSPATH')) {
    exit;
}

abstract class Velora_Club_Base_Blocks
{
    /**
     * Returns the BLOCKS configuration map:
     *   block-name => ['shortcode' => string, 'attributes' => array]
     */
    abstract protected static function get_blocks(): array;

    /** Script handle for the editor bundle, e.g. 'velora-breeder-blocks-editor'. */
    abstract protected static function editor_script_handle(): string;

    /** Absolute filesystem path to blocks/editor.js. */
    abstract protected static function editor_js_path(): string;

    /** Public URL of blocks/editor.js. */
    abstract protected static function editor_js_url(): string;

    /**
     * Plugin text domain as a plain string literal, e.g. 'velora-breeder-widgets'.
     * Used for the JavaScript translations of the block editor UI.
     */
    abstract protected static function text_domain(): string;

    /** Absolute filesystem path to the plugin's languages/ directory (no trailing /). */
    abstract protected static function languages_path(): string;

    public static function init(): void
    {
        add_action('init', [static::class, 'register_blocks']);
        add_action('enqueue_block_editor_assets', [static::class, 'enqueue_editor_assets']);
    }

    public static function register_blocks(): void
    {
        if (!function_exists('register_block_type')) {
            return; // Pre-Gutenberg WordPress.
        }
        foreach (static::get_blocks() as $name => $cfg) {
            register_block_type($name, [
                'attributes'      => $cfg['attributes'],
                'render_callback' => function ($attrs) use ($cfg) {
                    return static::render_via_shortcode($cfg['shortcode'], $attrs);
                },
            ]);
        }
    }

    /**
     * Builds a shortcode string from block attributes and delegates rendering.
     *
     * Keeps shortcode as the single source of truth for widget output — the
     * Gutenberg editor preview sees the same HTML the front-end sees.
     * Empty/null attribute values are skipped to keep the shortcode clean.
     */
    protected static function render_via_shortcode(string $shortcode, array $attrs): string
    {
        $atts_str = '';
        foreach ($attrs as $key => $value) {
            if ($value === '' || $value === null) {
                continue;
            }
            $atts_str .= ' ' . $key . '="' . esc_attr((string) $value) . '"';
        }
        return do_shortcode('[' . $shortcode . $atts_str . ']');
    }

    public static function enqueue_editor_assets(): void
    {
        $editor_path = static::editor_js_path();
        if (!file_exists($editor_path)) {
            return;
        }
        // filemtime() = automatic cache bust on every editor.js edit. Otherwise
        // newly added blocks stay invisible until users hard-refresh WP admin.
        wp_enqueue_script(
            static::editor_script_handle(),
            static::editor_js_url(),
            ['wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n'],
            (string) filemtime($editor_path),
            true
        );

        // Block titles and control labels live in editor.js and go through
        // wp.i18n.__(). A .mo file only reaches PHP — the editor needs the
        // JSON translation files generated by `wp i18n make-json`.
        wp_set_script_translations(
            static::editor_script_handle(),
            static::text_domain(),
            static::languages_path()
        );
    }
}
